NilFoundation/zkllvm-assigner

include/nil/blueprint/fields/addition.hpp
include/nil/blueprint/fields/division.hpp
include/nil/blueprint/fields/multiplication.hpp
include/nil/blueprint/fields/subtraction.hpp
include/nil/blueprint/parser.hpp
include/nil/blueprint/stack.hpp

Non native arithmetic handling

---

include/nil/blueprint/parser.hpp

Support handling constants as instruction operands

---

include/nil/blueprint/parser.hpp

Branch and comparison instructions supported

---

include/nil/blueprint/fields/addition.hpp
include/nil/blueprint/fields/division.hpp
include/nil/blueprint/fields/multiplication.hpp
include/nil/blueprint/fields/subtraction.hpp

Builtin field and curve types usage update

---

include/nil/blueprint/fields/addition.hpp
include/nil/blueprint/fields/division.hpp
include/nil/blueprint/fields/multiplication.hpp
include/nil/blueprint/fields/subtraction.hpp
include/nil/blueprint/memory.hpp
include/nil/blueprint/parser.hpp
include/nil/blueprint/stack.hpp

Add memory instruction handling, refactor frame

---

include/nil/blueprint/parser.hpp

Switch hash components to intrinsics

---

include/nil/blueprint/gep_resolver.hpp
include/nil/blueprint/memory.hpp
include/nil/blueprint/parser.hpp

Support initialization and indexing of complex structs

---

include/nil/blueprint/gep_resolver.hpp

fix: include header file for unordered_map

---

include/nil/blueprint/parser.hpp

Support curve and non-native fields in load/store

---

include/nil/blueprint/parser.hpp

Fix segfault in store handling

---

include/nil/blueprint/parser.hpp
include/nil/blueprint/public_input.hpp

JSON public input

---

include/nil/blueprint/parser.hpp
include/nil/blueprint/public_input.hpp

Support vector comparison, make public input error more readable

---

include/nil/blueprint/parser.hpp

Support handling undef values

---

include/nil/blueprint/asserts.hpp
include/nil/blueprint/gep_resolver.hpp
include/nil/blueprint/parser.hpp

Implement insertvalue and extractvalue, fix bugs in gep

---

include/nil/blueprint/parser.hpp

SHA2-256 handling updated

---

include/nil/blueprint/parser.hpp

Fix handling of global variables

---

CMakeLists.txt
include/nil/blueprint/logger.hpp
include/nil/blueprint/parser.hpp

Implement instruction logging

---

include/nil/blueprint/curves/addition.hpp
include/nil/blueprint/curves/multiplication.hpp
include/nil/blueprint/hashes/sha2_256.hpp
include/nil/blueprint/hashes/sha2_512.hpp
include/nil/blueprint/parser.hpp
include/nil/blueprint/public_input.hpp

Handle curve25519 curve addition and multiplication, sha2-512 intrinsic handling, modify public input reader to read arrays of non-native field and curve elements. Closes #100, #97,  #72

Read arrays of non-native fields and curves, handle 25519 curve addition and multiplication, handle sha2-512 intrinsic

---

include/nil/blueprint/comparison/comparison.hpp
include/nil/blueprint/parser.hpp

Temporarily remove blueprint component call from comparison eq

Fix rust CI

---

include/nil/blueprint/bitwise/and.hpp
include/nil/blueprint/bitwise/or.hpp
include/nil/blueprint/bitwise/xor.hpp
include/nil/blueprint/parser.hpp

Naive handling is added for bitwise operations until we have special components for them.

Bitwise and, or and xor naive handling added.

---

include/nil/blueprint/parser.hpp

Added print of the assignment table final result variables.
Closes https://github.com/NilFoundation/zkllvm/issues/212

Final result print added

---

CMakeLists.txt
include/nil/blueprint/asserts.hpp
include/nil/blueprint/comparison/comparison.hpp
include/nil/blueprint/curves/addition.hpp
include/nil/blueprint/curves/init.hpp
include/nil/blueprint/curves/multiplication.hpp
include/nil/blueprint/curves/subtraction.hpp
include/nil/blueprint/fields/addition.hpp
include/nil/blueprint/fields/division.hpp
include/nil/blueprint/fields/multiplication.hpp
include/nil/blueprint/fields/subtraction.hpp
include/nil/blueprint/gep_resolver.hpp
include/nil/blueprint/hashes/sha2_256.hpp
include/nil/blueprint/hashes/sha2_512.hpp
include/nil/blueprint/integers/addition.hpp
include/nil/blueprint/integers/bit_shift.hpp
include/nil/blueprint/integers/division.hpp
include/nil/blueprint/integers/division_remainder.hpp
include/nil/blueprint/integers/multiplication.hpp
include/nil/blueprint/integers/subtraction.hpp
include/nil/blueprint/logger.hpp
include/nil/blueprint/memory.hpp
include/nil/blueprint/parser.hpp
include/nil/blueprint/public_input.hpp

Spdlog replaced with Boost.Log2

---

include/nil/blueprint/boolean/logic_ops.hpp
include/nil/blueprint/comparison/comparison.hpp
include/nil/blueprint/input_reader.hpp
include/nil/blueprint/parser.hpp

Remove non-PI values from PI column that weren't removed before

339 clean pi continue

---

CMakeLists.txt
include/nil/blueprint/logger.hpp
include/nil/blueprint/parser.hpp

Logger replacement with Boost.Log2 [2]

---

include/nil/blueprint/input_reader.hpp
include/nil/blueprint/layout_resolver.hpp
include/nil/blueprint/memory.hpp
include/nil/blueprint/parser.hpp

Fix bugs with sret and memcpy

---

include/nil/blueprint/assigner.hpp

Fix missed renaming of variable.

Hotfix after refactoring

---

include/nil/blueprint/input_reader.hpp

Closes https://github.com/NilFoundation/zkLLVM/issues/555

Fix int parsing and arg num checking in input reader
